includes:
- configs/MPTraj/Perovskites/gemnet-dT-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_labels_folder: labels/MPtraj_labels/mace_mp_all_splits_Perovskites_noIons

loss_functions:
  - energy:
      fn: mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 100
      reduction: mean_all

optim:
  batch_size: 16
  eval_batch_size: 32
  force_jac_sample_size: 1
  print_memory_usage: False
  vectorize_jacs: True
