
logger: 
  name: wandb
  project: EGAP

trainer: ocp

dataset:
  train:
    format: lmdb
    src: /data/shared/MLFF/MD22/95_lmdb/AT-AT/train/
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        energy:
          mean: -26913.953
          stdev: 0.35547638
        forces:
          mean: 0
          stdev: 1.1291506
  val:
    src: /data/shared/MLFF/MD22/95_lmdb/AT-AT/val/


outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 1
  - forces:
      fn: l2mae
      coefficient: 100
evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
