includes:
- configs/OC20/Halides_2M/gemnet-dT.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    # teacher_checkpoint_path: /data/ishan-amin/OC20_teacher_checkpoints/eq2_31M_ec4_allmd.pt
    teacher_checkpoint_path: /data/ishan-amin/OC20_teacher_checkpoints/gemnet_oc_large_s2ef_all_md.pt
    teacher_labels_folder: labels/Halides_eq2_31M_ec4_allmd
    # teacher_labels_folder: labels/Halides_gemnet_oc_large_s2ef_all_md
    label_force_batch_size: 1
    label_jac_batch_size: 1
    vectorize_teach_jacs: False

loss_functions:
  - energy:
      fn: mae
      coefficient: 0
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 100
      reduction: mean_all

optim:
  batch_size: 16
  eval_batch_size: 32
  force_jac_sample_size: 4
  print_memory_usage: False
  vectorize_jacs: True
