includes:
- configs/OC20/Halides_2M/gemnet-dT.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    # teacher_checkpoint_path: /data/ishan-amin/OC20_teacher_checkpoints/gemnet_oc_large_s2ef_all_md.pt
    # teacher_checkpoint_path:  /pscratch/sd/i/ishan_a/OC20_teacher_checkpoints/eq2_31M_ec4_allmd.pt
    # teacher_labels_folder: /pscratch/sd/i/ishan_a/OC20_labels/Halides_eq2_31M_ec4_allmd
    teacher_labels_folder: /pscratch/sd/i/ishan_a/OC20_labels/Halides_gemnet_oc_base_s2ef_all_md

    label_force_batch_size: 1
    label_jac_batch_size: 1
    vectorize_teach_jacs: True
    
loss_functions:
  - energy:
      fn: mae
      coefficient: .0001
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 50
      reduction: mean_all

optim:
  batch_size: 16
  force_jac_sample_size: 1
  print_memory_usage: False
  vectorize_jacs: True
