# Make sure to run without AMP.
includes:
- configs/SPICE/solvated_amino_acids/base.yml

dataset:
  train:
    transforms:
      normalizer:
        energy: 
            mean: -322.07 #  actual formation energy value for solvated
            stdev: 1 #idk how to actually deal with the scaling issue, so we'll go with 1.  20.60 is actual formation energy value for solvated
        forces: 
            mean: 0   # actual for forces: 0
            stdev: 1  # actual for std: 1.549

model:
  name: painn
  hidden_channels: 128
  num_layers: 4
  num_rbf: 128
  cutoff: 12.0
  max_neighbors: 50
  scale_file: configs/SPICE/solvated_amino_acids/painn/painn-small-scale.pt
  regress_forces: True
  direct_forces: False # note: this is the main difference here
  use_pbc: True # Let's try true for this....
  otf_graph: True

optim:
  batch_size: 8
  eval_batch_size: 32
  load_balancing: atoms
  num_workers: 4
  optimizer: AdamW
  optimizer_params: {"eps": 1.e-7, "weight_decay": 0.000002, "amsgrad": True}
  lr_initial: 1.e-3 
  scheduler: ReduceLROnPlateau
  patience: 10
  factor: 0.8
  min_lr: 0.000005
  max_epochs: 10000
  ema_decay: 0.999
  clip_grad_norm: 10


