includes:
- configs/SPICE/monomers/gemnet-dT-smaller.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_checkpoint_path: checkpoints/2024-08-23-10-04-00-MonomersGemSmaller/best_checkpoint.pt
    teacher_labels_folder: labels/mace_off_medium_SpiceMonomers1k
    # teacher_labels_folder: labels/mace_off_large_SpiceMonomers
    # teacher_labels_folder: labels/MonomersgemSmaller
    label_force_batch_size: 32
    label_jac_batch_size: 4
    vectorize_teach_jacs: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 0
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 400
      reduction: mean_all

optim:
  batch_size: 8
  eval_batch_size: 32
  force_jac_sample_size: 30
  print_memory_usage: False
  vectorize_jacs: True
