includes:
- configs/OC20/200k/gemnet/gemnet-dT.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_checkpoint_path: checkpoints/eq2_31M_ec4_allmd.pt
    teacher_labels_folder: labels/eq2_31M_ec4_allmd_on10k
    label_force_batch_size: 4
    label_jac_batch_size: 8
    vectorize_teach_jacs: False

loss_functions:
  - energy:
      fn: mae
      coefficient: 1
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 400
      reduction: mean_all

optim:
  batch_size: 4
  eval_batch_size: 32
  force_jac_sample_size: 30
  print_memory_usage: False
  vectorize_jacs: True
