includes:
  - configs/slurm/premium.yml
logger: 
  name: wandb
  project: spice-Energy

trainer: ocp

dataset:
  train:
    format: lmdb
    src: data/SPICE/spice_seperated_w_energies/DES370K_Monomers/train
    key_mapping:
      reference_energy: energy
      force: forces
    transforms:
      normalizer:
        energy: 
            mean: -140.80356519035792 # eric number
            stdev: 69.1667169308504   # eric number
            # mean: -1500.67354  # true mean for monomers: -1500.67354
            # stdev: 3261.3593    # true std for monomers: 3261.3593 - note that these are energy per atom
        forces: 
            mean: 0 
            stdev: 1          # true std: .9473
  val:
    src: data/SPICE/spice_seperated_w_energies/DES370K_Monomers/val


outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 100
evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
