trainer: ocp

dataset:
  train:
    format: lmdb
    src: /data/ishan-amin/OC20_seperated/Halides/train
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        forces:
          mean: 0
          stdev: 2.887317180633545
  val:
    src: /data/ishan-amin/OC20_seperated/Halides/val

logger: wandb

outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 0
  - forces:
      fn: l2mae
      coefficient: 100

evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
