includes:
  # - configs/slurm/regular.yml
  - configs/slurm/premium.yml
  # - configs/slurm/debug.yml

trainer: ocp

logger: 
  name: wandb
  project: OC-20

dataset:
  train:
    teacher_checkpoint_path:  /pscratch/sd/i/ishan_a/OC20_teacher_checkpoints/gemnet_oc_large_s2ef_all_md.pt
    teacher_labels_folder: /pscratch/sd/i/ishan_a/OC20_labels/Halides_gemnet_oc_base_s2ef_all_md
    format: lmdb
    # src: /data/ishan-amin/OC20_seperated/Halides/train
    src: /pscratch/sd/i/ishan_a/OC20_seperated/Halides/train
    no_shuffle: True
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        energy:
          mean: -0.7554450631141663
          stdev: 2.887317180633545
        forces:
          mean: 0
          stdev: 2.887317180633545
  val:
    # src: /data/ishan-amin/OC20_seperated/Halides/val
    src: /pscratch/sd/i/ishan_a/OC20_seperated/Halides/val
    no_shuffle: True


outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 0
  - forces:
      fn: l2mae
      coefficient: 100

evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
