includes:
- configs/OC20/Halides_2M/base.yml

model:
  name: gemnet_t
  num_spherical: 7
  num_radial: 128
  num_blocks: 4 # originally 3, changed to 4 to match with spice
  emb_size_atom: 64 # smaller from 512 #used to be 64
  emb_size_edge: 64 # smaller from 512 # used to be 64
  emb_size_trip: 32 # smaller from 64 # used to be 32
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_bil_trip: 64
  num_before_skip: 1
  num_after_skip: 2
  num_concat: 1
  num_atom: 3
  cutoff: 12.0 #used to be 6.0
  otf_graph: True
  max_neighbors: 30 # used to be 50
  rbf:
    name: gaussian
  envelope:
    name: polynomial
    exponent: 5
  cbf:
    name: spherical_harmonics
  extensive: True
  output_init: HeOrthogonal
  activation: silu
  scale_file: configs/OC20/Halides_2M/gemnet-4l-64h.pt

  regress_forces: True
  direct_forces: True

optim:
  batch_size: 16
  eval_batch_size: 32
  # eval_every: 15000 #upped from 5k
  num_workers: 4
  lr_initial: 5.e-4
  optimizer: AdamW
  optimizer_params: {"amsgrad": True}
  scheduler: ReduceLROnPlateau
  mode: min
  factor: 0.8
  patience: 3
  max_epochs: 1000 #upped from 80 (we're using a smaller dataset ig)
  ema_decay: 0.999
  clip_grad_norm: 10
