includes:
- /home/ishan-amin/MLFF-distill/configs/md17/ethanol/gemnet-dT-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_checkpoint_path: teacher_checkpoints/ethanol_50k_gemnet_t/best_checkpoint.pt
    # teacher_labels_folder: labels/ethanol_50k_gemnet_t_1k_labels
    teacher_labels_folder: labels/mace_mp0_large_ethonal1k
    label_force_batch_size: 32
    label_jac_batch_size: 64
    vectorize_teach_jacs: True

loss_functions:
  - energy:
      fn: mae
      coefficient: .25
  - forces:
      fn: l2mae
      coefficient: 250
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 1000
      reduction: mean_all

optim:
  batch_size: 8
  eval_batch_size: 32
  force_jac_sample_size: 30
  print_memory_usage: False
  vectorize_jacs: True
