includes:
  - configs/slurm/regular.yml
  # configs/slurm/debug.yml
logger: 
  name: wandb
  entity: ishan-amin
  project: spice

trainer: ocp

dataset:
  train:
    no_shuffle: True
    format: lmdb
    src: data/SPICE/spice_separated/Solvated_Amino_Acids/train
    teacher_labels_folder: /pscratch/sd/i/ishan_a/labels/mace_off_large_SpiceAminos
    format: lmdb
    src: /pscratch/sd/i/ishan_a/spice_separated/Solvated_Amino_Acids/train
    key_mapping:
      reference_energy: energy
      force: forces
    transforms:
      normalizer:
        energy: 
            mean: -322.07 #  actual formation energy value for solvated
            stdev: 20.60 #idk how to actually deal with the scaling issue, so we'll go with 1.  20.60 is actual formation energy value for solvated
        forces: 
            mean: 0   # actual for forces: 0
            stdev: 1  # actual for std: 1.549
  val:
    src: /pscratch/sd/i/ishan_a/spice_separated/Solvated_Amino_Acids/val
  test:
    src: /pscratch/sd/i/ishan_a/spice_separated/Solvated_Amino_Acids/test


outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 5
  - forces:
      fn: l2mae
      coefficient: 100
evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
