includes:
- configs/OC20/Nonmetals_N_in_adsorbate/gemnet-dT.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_checkpoint_path:  /pscratch/sd/i/ishan_a/OC20_teacher_checkpoints/gemnet_oc_large_s2ef_all_md.pt
    teacher_labels_folder: /pscratch/sd/i/ishan_a/OC20_labels/Nonmetals_N_in_adsorbate_gemnet_oc_large_s2ef_all_md_final
    label_force_batch_size: 1
    label_jac_batch_size: 1
    vectorize_teach_jacs: False

loss_functions:
  - energy:
      fn: mae
      coefficient: 0
  - forces:
      fn: l2mae
      coefficient: 100
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 50
      reduction: mean_all

optim:
  batch_size: 8
  force_jac_sample_size: 4
  print_memory_usage: False
  vectorize_jacs: True
