includes:
- configs/md17/ethanol/base.yml

model:
  name: schnet
  hidden_channels: 32
  num_filters: 32
  num_interactions: 6
  num_gaussians: 25
  cutoff: 5.0
  use_pbc: False
  otf_graph: True

optim:
  batch_size: 32
  eval_batch_size: 100
  num_workers: 8
  lr_initial: 0.0001
  lr_gamma: 0.1
  optimizer: Adam
  warmup_steps: 5000
  warmup_factor: 0.2
  max_epochs: 1000
  scheduler: ReduceLROnPlateau
  patience: 30
  factor: 0.8
  min_lr: 0.000001