includes:
- configs/OC20/Nonmetals_N_in_adsorbate/painn/painn_h128_L4.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    label_force_batch_size: 1
    label_jac_batch_size: 1
    vectorize_teach_jacs: False

model:
  use_teacher_atom_embeddings: True

outputs:
  final_node_features:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 0
  - forces:
      fn: l2mae
      coefficient: 200
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - final_node_features:
      fn: mse
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 0
      reduction: mean_all

evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    final_node_features:
      - mse
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae

optim:
  batch_size: 8
  force_jac_sample_size: 4
  print_memory_usage: False
  vectorize_jacs: True
