includes:
  - configs/slurm/premium.yml

trainer: ocp

logger: 
  name: wandb
  entity: ishan-amin
  project: MPTraj


dataset:
  train:
    no_shuffle: True
    teacher_checkpoint_path:  /pscratch/sd/i/ishan_a/OC20_teacher_checkpoints/gemnet_oc_large_s2ef_all_md.pt
    teacher_labels_folder: /pscratch/sd/i/ishan_a/OC20_labels/Nonmetals_N_in_adsorbate_gemnet_oc_large_s2ef_all_md_final
    format: lmdb
    src: data/MPtraj/mptraj_seperated_all_splits/Yttrium/train

trainer: ocp

dataset:
  train:
    no_shuffle: True
    teacher_labels_folder: /pscratch/sd/i/ishan_a/MPtraj_labels/mace_mp_all_splits_Yttrium
    format: lmdb
    src: /pscratch/sd/i/ishan_a/mptraj_seperated_all_splits/Yttrium/train

    key_mapping:
      corrected_total_energy: energy
      force: forces
    transforms:
      normalizer:
        forces: 
            mean: 0
            stdev: 1
  val:
    src: data/MPtraj/mptraj_seperated_all_splits/Yttrium/val


outputs:
  energy:
    shape: 1
    level: system
  forces:
    irrep_dim: 1
    level: atom
    train_on_free_atoms: True
    eval_on_free_atoms: True

loss_functions:
  - energy:
      fn: mae
      coefficient: 0
  - forces:
      fn: l2mae
      coefficient: 100
evaluation_metrics:
  metrics:
    energy:
      - mae
    forces:
      - mae
      - cosine_similarity
      - magnitude_error
    misc:
      - energy_forces_within_threshold
  primary_metric: forces_mae
