includes:
- configs/md22/AT-AT/gemnet-dT-small.yml

trainer: src.distill_trainer.DistillTrainer

dataset:
  train:
    teacher_checkpoint_path: teacher_checkpoints/AT-AT_gem_T_nonNorm_500k/best_checkpoint.pt
    teacher_labels_folder: labels/AT_AT_all_gemnet_t_proper
    # teacher_labels_folder: /pscratch/sd/i/ishan_a/labels/AT_AT_all_gemnet_t
    teacher_scale_file: configs/md22/AT-AT/gemnet-T-scale.json
    label_force_batch_size: 32
    label_jac_batch_size: 64
    vectorize_teach_jacs: False

loss_functions:
  - energy:
      fn: mae
      coefficient: .25
  - forces:
      fn: l2mae
      coefficient: 25
  - teacher_forces:
      fn: l2mae
      coefficient: 0
  - force_jacs:
      fn: l2mae
      coefficient: 100
      reduction: mean_all

optim:
  batch_size: 4
  eval_batch_size: 32
  force_jac_sample_size: 60
  print_memory_usage: False
  vectorize_jacs: True
